# this python script is for adding a slug field to the JSON data, which is a URL-friendly version of the product name or style code.
# The slug will be generated by taking the product name or style code, converting it to lowercase, replacing spaces and special characters with hyphens, and removing any non-alphanumeric characters.

# import json to handle JSON data
import json

# import the base directory path from the settings file to construct the path to the JSON file
from fashionbroda.settings import BASE_DIR

# import the Path class from the pathlib module to handle file paths in a platform-independent way

# try catch block to handle potential errors when reading the JSON file, such as file not found or invalid JSON format
try:
    json_file_path = (
        BASE_DIR
        / "fashionbroda"
        / "fashionbroda"
        / "scraped_data"
        / "images_paths.json"
    )
    # open the JSON file in read mode with UTF-8 encoding to ensure that any special characters are handled correctly
    with open(json_file_path, "r", encoding="utf-8") as json_file:
        # load the JSON data from the file
        # this returns a list of dictionaries, where each dictionary represents an album with its associated metadata, this is the data that we will be using to schedule the album pages for scraping
        data = json.load(json_file)

# account for exceptions that may occur during file reading
# account for the file not being found error
except FileNotFoundError:
    # log the error message that the JSON file was not found at the specified path, this is useful for debugging and monitoring the scraping process, to identify any issues with missing files
    print(f"JSON file not found at: {json_file_path}")
    raise SystemExit("JSON file not found")
# account for JSON decoding errors, which occur when the file is not in valid JSON format
except json.JSONDecodeError as e:
    print(f"Invalid JSON format: {e}")
    raise SystemExit("Invalid JSON file")
# account for any other unexpected exceptions that may occur during file reading
except Exception as e:
    print(f"Unexpected error reading JSON file: {e}")
    raise SystemExit("Error reading JSON file")


# this function takes a category string as input, removes any leading or trailing whitespace using the strip() method,
# and converts the string to lowercase using the lower() method. This normalization process ensures that the category is in a consistent format, which can be useful for tasks such as categorization, filtering, or generating slugs for URLs.
def normalize_category(category):
    return category.strip().lower()


# extract the album hash, and pass the argument images_path, which is a string representing the path to the album images.
def extract_album_hash(images_path):
    # check the Images_path variable (ln-77) to ensure that it is not empty or None before attempting to split it.
    if not images_path:
        # If images_path is empty or None, the function will return None, which can help prevent errors when trying to access parts of the path that do not exist.
        return None

    # then split the path using the split() method with "/" as the delimiter, which will break the path into its individual components (e.g., directories and file names). The resulting list of components is stored in the variable parts.
    parts = images_path.split("/")
    # check if the resulting list has more than 2 components (i.e., it has at least 3 components),
    if len(parts) > 2:
        # and if so, return the third component (index 2) as the album hash. This assumes that the album hash is located at this specific position in the path.
        return parts[2]
    # If the list does not have more than 2 components, the function will return None, indicating that the album hash could not be extracted from the path.
    return None


# generate the slug
def generate_slug(category, extracted_album_hash):
    # combine the normalized category and the extracted album hash to create a slug,
    # which is a URL-friendly string that can be used in web addresses. The slug is generated by concatenating the normalized category and the extracted album hash with a hyphen in between.
    # This format helps to create unique and descriptive slugs for each album based on its category and unique identifier (album hash), which can improve SEO and make URLs more user-friendly.
    return f"{category}-{extracted_album_hash}"


for item in data:
    # extract the category and images_path from the item dictionary
    category = item.get("category", "")

    # Try to get images path from product_images_paths first, then size_chart_images_paths
    product_images = item.get("product_images_paths", [])
    size_chart_images = item.get("size_chart_images_paths", [])
    # initialise the variable images_path with an empty string to ensure that it has a default value, which can help prevent errors in cases where both product_images_paths and size_chart_images_paths are empty or not present in the item dictionary.
    images_path = ""
    # check if product_images_paths is not empty and has at least one element,
    if product_images and len(product_images) > 0:
        # if so, assign the first element of product_images_paths to images_path.
        images_path = product_images[0]
    # If product_images_paths is empty or does not have any elements, check if size_chart_images_paths is not empty and has at least one element,
    elif size_chart_images and len(size_chart_images) > 0:
        # if so, assign the first element of size_chart_images_paths to images_path.
        # This logic ensures that we prioritize using the product images path for slug generation, but if it's not available, we fall back to using the size chart images path.
        images_path = size_chart_images[0]

    # normalize the category using the normalize_category function
    normalized_category = normalize_category(category)

    # extract the album hash from the images_path using the extract_album_hash function
    album_hash = extract_album_hash(images_path)

    # if both the normalized category and album hash are successfully extracted, generate the slug
    if normalized_category and album_hash:
        slug = generate_slug(normalized_category, album_hash)
        # add the generated slug to the item dictionary under the key "slug"
        item["slug"] = slug
    else:
        # if either the category or album hash is missing, log a warning message indicating that the slug could not be generated for this item, which can help with debugging and ensuring data integrity.
        print(
            f"Warning: Could not generate slug for item with category '{category}' and images_path '{images_path}'"
        )

# Save updated file (optional)
output_path = BASE_DIR / "fashionbroda" / "fashionbroda" / "scraped_data" / "slug.json"

with open(output_path, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2)

print("Slug generation complete.")
